#!/bin/bash
# Generate the basis-for-verdict report for the PacBio biological filtering stage.
#
# Why this exists: an intactness caller returns a single verdict per sequence --
# "intact" or a defect category -- and that verdict is only meaningful for the
# parts of the genome that were actually sequenced. These are amplicon libraries
# covering 12-92% of the genome, so a bare "defective" call is ambiguous between
# "a real defect was observed" and "the gene carrying the defect was never read".
#
# This report therefore pairs every call with per-gene read coverage, so each
# gene is explicitly assessable or not-assessable, and a verdict is only credited
# where the evidence exists. Coverage is read from the assembly stage's mask BED
# in REFERENCE coordinates, and gene boundaries from HXB2's own GenBank record,
# so nothing here is hardcoded.
#
# Usage: report_pacbio_biological_filtering.sh [ASSEMBLY_ARM] [output.md]
set -euo pipefail

REPO_ROOT=""
for CAND in "${SLURM_SUBMIT_DIR:-}" \
            "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)" \
            "$(pwd)"; do
    if [ -n "${CAND}" ] && [ -d "${CAND}/scripts" ] && [ -d "${CAND}/results" ]; then
        REPO_ROOT="${CAND}"; break
    fi
done
[ -n "${REPO_ROOT}" ] || { echo "ERROR: cannot locate repo root." >&2; exit 1; }

ARM="${1:-${ASSEMBLY_ARM:-minimap2_consensus}}"
BF_DIR="${REPO_ROOT}/results/biological_filtering/pacbio/${ARM}"
ASM_DIR="${REPO_ROOT}/results/assembly/pacbio/${ARM}_out"
GB="${REPO_ROOT}/data/reference/K03455.1.gb"
OUT="${2:-${BF_DIR}/intactness_basis_report.md}"

[ -d "${BF_DIR}" ] || { echo "ERROR: ${BF_DIR} not found -- run the stage first." >&2; exit 1; }

SAMPLES=$(ls -1 "${ASM_DIR}"/*_consensus.fasta 2>/dev/null | while read -r f; do
              b=$(basename "${f}"); echo "${b%_consensus.fasta}"; done)
[ -n "${SAMPLES}" ] || { echo "ERROR: no consensus FASTAs in ${ASM_DIR}." >&2; exit 1; }

# --- HXB2 CDS exons -----------------------------------------------------------
# HXB2 labels its CDS features with /note=, not /gene=, and spliced genes use
# join(a..b,c..d); every exon is emitted separately so coverage sums correctly.
GENES_TSV=$(mktemp)
awk '
  /^     CDS / { loc = $2; want = 1; next }
  want && /\/note=/ {
      g = $0; sub(/.*\/note="/, "", g); sub(/".*/, "", g)
      split(g, t, " "); name = t[1]
      tmp = loc; gsub(/join\(|\)/, "", tmp)
      n = split(tmp, parts, ",")
      for (i = 1; i <= n; i++)
          if (parts[i] ~ /^[0-9]+\.\.[0-9]+$/) { split(parts[i], a, "\\.\\."); print name, a[1], a[2] }
      want = 0
  }
' "${GB}" > "${GENES_TSV}"
GENES=$(awk '{print $1}' "${GENES_TSV}" | awk '!seen[$0]++')

# percent of a gene covered by reads, from the mask BED
gene_cov() {
    local gene="$1" bed="$2"
    [ -s "${bed}" ] || { echo 0; return; }
    awk -v g="${gene}" -v bed="${bed}" '
        $1 == g {
            gs = $2; ge = $3; total += ge - gs + 1
            while ((getline line < bed) > 0) {
                split(line, b, "\t"); ms = b[2] + 1; me = b[3]
                lo = (ms > gs ? ms : gs); hi = (me < ge ? me : ge)
                if (hi >= lo) masked += hi - lo + 1
            }
            close(bed)
        }
        END { if (total > 0) printf "%.0f", 100*(total - masked)/total; else printf "0" }
    ' "${GENES_TSV}"
}

mkdir -p "$(dirname "${OUT}")"
{
printf '# PacBio biological filtering -- basis for intact vs defective\n\n'
printf '**Arm:** `%s`  ·  **Generated:** %s  ·  auto-generated by `scripts/utils/report_pacbio_biological_filtering.sh`\n\n' \
       "${ARM}" "$(date +%Y-%m-%d)"
printf 'An intactness verdict only means something for genes that were sequenced.\n'
printf 'These are amplicon libraries, so each gene below is marked **assessable**\n'
printf '(fully covered by reads) or **not assessable**, and defect calls are only\n'
printf 'credited where the evidence exists.\n\n'
printf '%s **assessable** -- gene is 100%% covered by reads. A defect call here is a finding.\n' '-'
printf '%s **partial** -- gene is partly covered. A defect may be real; absence of one proves nothing.\n' '-'
printf '%s **not assessable** -- gene has no read coverage. Any call is reference-derived.\n\n' '-'
printf '%s\n\n' '---'

# ---------------- subtype actually used ----------------
printf '## Reference subtype used per sequence\n\n'
printf 'HIVIntact scores against a subtype-specific reference, so the subtype must match\n'
printf 'the sequence. Scoring the whole batch as A1 previously reported HXB2 itself as\n'
printf 'defective; each record is now scored on its own.\n\n'
MANIFEST="${BF_DIR}/hivintact_out/per_sample_subtype.tsv"
if [ -s "${MANIFEST}" ]; then
    printf '| sequence | subtype used | source |\n|---|---|---|\n'
    awk -F'\t' 'NR>1 {printf "| %s | %s | %s |\n", $1, $2, $3}' "${MANIFEST}"
else
    printf '_No `per_sample_subtype.tsv` -- stage predates the per-sample subtype fix._\n'
fi
printf '\n'

# ---------------- per-gene coverage ----------------
printf '## Per-gene read coverage\n\n'
printf 'From `%s_out/<sample>.uncovered.bed` and HXB2 CDS annotation. HXB2 uses archaic\n' "${ARM}"
printf 'CDS labels: `sor`=vif, `R`=vpr, `trs`=rev, `27K`=nef.\n\n'
printf '| gene | CDS bp |'
for S in ${SAMPLES}; do printf ' %s |' "${S}"; done
printf '\n|---|---|'
for S in ${SAMPLES}; do printf '---|'; done
printf '\n'
for G in ${GENES}; do
    LEN=$(awk -v g="${G}" '$1==g {n += $3-$2+1} END{print n}' "${GENES_TSV}")
    printf '| %s | %s |' "${G}" "${LEN}"
    for S in ${SAMPLES}; do
        PCT=$(gene_cov "${G}" "${ASM_DIR}/${S}.uncovered.bed")
        if   [ "${PCT}" -eq 100 ]; then MARK="**100%**"
        elif [ "${PCT}" -eq 0 ];   then MARK="0%"
        else                            MARK="${PCT}%"
        fi
        printf ' %s |' "${MARK}"
    done
    printf '\n'
done
printf '\n'

# ---------------- assessability summary ----------------
printf '### Genes assessable per sample\n\n'
printf '| sample | assessable (100%%) | partial | not assessable (0%%) |\n|---|---|---|---|\n'
for S in ${SAMPLES}; do
    FULL=""; PART=""; NONE=""
    for G in ${GENES}; do
        PCT=$(gene_cov "${G}" "${ASM_DIR}/${S}.uncovered.bed")
        if   [ "${PCT}" -eq 100 ]; then FULL="${FULL} ${G}"
        elif [ "${PCT}" -eq 0 ];   then NONE="${NONE} ${G}"
        else                            PART="${PART} ${G}(${PCT}%)"
        fi
    done
    printf '| %s |%s |%s |%s |\n' "${S}" "${FULL:- none}" "${PART:- none}" "${NONE:- none}"
done
printf '\n'

# ---------------- HIVIntact verdicts ----------------
printf '%s\n\n## HIVIntact verdicts\n\n' '---'
IO="${BF_DIR}/hivintact_out"
if [ -d "${IO}" ]; then
    printf '| sequence | verdict | errors reported |\n|---|---|---|\n'
    for D in "${IO}"/*/; do
        ID=$(basename "${D}")
        case "${ID}" in per_sample_input) continue ;; esac
        [ -f "${D}/errors.json" ] || continue
        NI=$(grep -c '^>' "${D}/intact.fasta" 2>/dev/null || echo 0)
        VERD=$([ "${NI:-0}" -gt 0 ] && echo "**intact**" || echo "defective")
        ERRS=$(grep -oE '"error": *"[^"]*"' "${D}/errors.json" 2>/dev/null \
               | sed 's/.*": *"//; s/"$//' | sort | uniq -c \
               | awk '{printf "%s(x%s); ", $2, $1}')
        printf '| %s | %s | %s |\n' "${ID}" "${VERD}" "${ERRS:-none}"
    done
else
    printf '_No `hivintact_out` directory._\n'
fi
printf '\n'

# ---------------- HIVSeqinR ----------------
printf '%s\n\n## HIVSeqinR\n\n' '---'
printf 'Input is split on runs of `N` so only sequenced segments are classified; nothing\n'
printf 'is substituted for unsequenced sequence. Primer autotrim was NOT performed (the\n'
printf 'SMRTcap 2nd-round primers are undocumented, so the author defaults remain).\n\n'
SEGREP="${BF_DIR}/hivseqinr_out/segments.tsv"
if [ -s "${SEGREP}" ]; then
    printf '| record | segment | length bp | IUPAC substitutions |\n|---|---|---|---|\n'
    awk -F'\t' 'NR>1 {printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4}' "${SEGREP}"
    printf '\n'
else
    printf '_No `segments.tsv` -- HIVSeqinR staging did not run._\n\n'
fi
HSCSV="${BF_DIR}/hivseqinr_out/Output_MyBigSummary_DF_FINAL.csv"
if [ -s "${HSCSV}" ]; then
    printf '### HIVSeqinR classifications\n\n```\n'
    head -20 "${HSCSV}"
    printf '```\n\n'
else
    printf '_No final summary CSV produced -- see `hivseqinr_out/hivseqinr.log`._\n\n'
fi

# ---------------- Poplars ----------------
printf '%s\n\n## Poplars (Hypermut 3)\n\n' '---'
POP="${BF_DIR}/poplars_out.tsv"
if [ -s "${POP}" ]; then
    printf 'Output rows: %s. APOBEC G->A hypermutation screen.\n\n' "$(wc -l < "${POP}")"
else
    printf '_No Poplars output._\n\n'
fi

# ---------------- the combined basis table ----------------
printf '%s\n\n## Basis for each verdict\n\n' '---'
printf 'The deliverable table: verdict alongside how much of the genome supports it.\n\n'
printf '| sample | genes assessable | genes not assessable | HIVIntact verdict | interpretation |\n'
printf '|---|---|---|---|---|\n'
NGENES=$(printf '%s\n' ${GENES} | wc -l)
for S in ${SAMPLES}; do
    NF=0; NN=0
    for G in ${GENES}; do
        PCT=$(gene_cov "${G}" "${ASM_DIR}/${S}.uncovered.bed")
        if [ "${PCT}" -eq 100 ]; then NF=$((NF+1)); fi
        if [ "${PCT}" -eq 0 ];   then NN=$((NN+1)); fi
    done
    D="${IO}/${S}"
    if [ -f "${D}/errors.json" ]; then
        NI=$(grep -c '^>' "${D}/intact.fasta" 2>/dev/null || echo 0)
        VERD=$([ "${NI:-0}" -gt 0 ] && echo "intact" || echo "defective")
    else
        VERD="not run"
    fi
    if   [ "${NF}" -eq 0 ]; then INTERP="**verdict unsupported** -- no gene fully sequenced"
    elif [ "${NN}" -gt 0 ]; then INTERP="partial -- verdict covers ${NF}/${NGENES} genes only"
    else                         INTERP="whole-genome verdict supported"
    fi
    printf '| %s | %s/%s | %s | %s | %s |\n' "${S}" "${NF}" "${NGENES}" "${NN}" "${VERD}" "${INTERP}"
done
printf '\n%s\n\nPer-run timings: `%s/summary.tsv`\n' '---' "${BF_DIR}"
} > "${OUT}"

rm -f "${GENES_TSV}"
echo "Wrote intactness basis report to ${OUT}"
